figure('Renderer', 'painters', 'Position', [10 10 300 1000])
plot(coreP, depth, ':m', 'LineWidth', 2, 'MarkerSize',2)
hold on
grid on
plot(ep, depth, 'b')
% plot(dp, depth, 'r')
% plot(np, depth, 'g')
%plot(tp, depth, 'g')
% plot(cdp, depth, 'm')
% plot(cnp, depth, 'g')
%plot(swc, depth,'r')
%set ( gca, 'xdir', 'reverse' )
%xlabel('irreducible water saturation(Swi)')
xlabel('porosity(frac)')
ylabel('Depth(m)')
%legend( 'core porosity','corrected density porosity','corrected neutron porosity','density porosity','neutron porosity', 'Location', 'northeast')
%xlabel('porosity and irreducible water saturation estimation')
legend('core porosity' , 'effective porosity', 'total porosity', 'irreducible water saturaion')
xlim([0, 1])
ylim([1885, 1960])
set(gca, 'XMinorTick','on', 'XMinorGrid','on')
set(gca, 'YMinorTick','on', 'YMinorGrid','on')
set(gca,'XAxisLocation','top','YAxisLocation','left','ydir','reverse')
